#include "blynk.h"
enum VPins {
    START_BUTTON = V0,
    STEP_TIME_REMAINING_DISP = V1,
    CURRENT_STATE_DISP = V2,
    ENDING_SOUND_SLIDER = V3,
    CUP_STATUS_DISP = V4,
    TEA_TYPE_SELECTOR = V5,
    TOTAL_TIME_REMAINING_DISP = V6,
};